repos:
  - repo: local
    hooks:
      - id: ruff-format
        language: python
        name: ruff-format
        pass_filenames: false
        entry: uv run ruff format fastapi_backports tests examples

  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        entry: uv run ruff check --fix --exit-non-zero-on-fix --show-fixes fastapi_backports tests

  - repo: local
    hooks:
      - id: ty
        language: python
        name: ty
        pass_filenames: false
        entry: uv run ty check fastapi_backports
